version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: nutrifit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_nutrifit
    ports:
      - "9902:5432"
    volumes:
      - "pgdata:/var/lib/postgresql"
    networks:
      - nutrifit

volumes:
  pgdata:
    driver: local

networks:
  nutrifit:
    name: nutrifit.networks
